# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dasom
email: your-email@domain.com
description: A multilingual input method framework
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dasom-im.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  dasom-im

# Build settings
markdown: kramdown
